In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
from sklearn.datasets import load_iris

In [17]:
data=load_iris()

In [18]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [19]:
df=pd.DataFrame(data=data['data'],columns=data['feature_names'])

In [20]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [21]:
df['Target']=data['target']

In [22]:
df.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  Target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [23]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [24]:
df["Flower_name"]=df['Target'].apply(lambda x: data['target_names'][x])

In [25]:
df.head()

   sepal length (cm)  sepal width (cm)  ...  Target  Flower_name
0                5.1               3.5  ...       0       setosa
1                4.9               3.0  ...       0       setosa
2                4.7               3.2  ...       0       setosa
3                4.6               3.1  ...       0       setosa
4                5.0               3.6  ...       0       setosa

[5 rows x 6 columns]

In [26]:
df[df['Target']==1]

    sepal length (cm)  sepal width (cm)  ...  Target  Flower_name
50                7.0               3.2  ...       1   versicolor
51                6.4               3.2  ...       1   versicolor
52                6.9               3.1  ...       1   versicolor
53                5.5               2.3  ...       1   versicolor
54                6.5               2.8  ...       1   versicolor
55                5.7               2.8  ...       1   versicolor
56                6.3               3.3  ...       1   versicolor
57                4.9               2.4  ...       1   versicolor
58                6.6               2.9  ...       1   versicolor
59                5.2               2.7  ...       1   versicolor
60                5.0               2.0  ...       1   versicolor
61                5.9               3.0  ...       1   versicolor
62                6.0               2.2  ...       1   versicolor
63                6.1               2.9  ...       1   versicolor
64                5.6               2.9  ...       1   versicolor
65                6.7               3.1  ...       1   versicolor
66                5.6               3.0  ...       1   versicolor
67                5.8               2.7  ...       1   versicolor
68                6.2               2.2  ...       1   versicolor
69                5.6               2.5  ...       1   versicolor
70                5.9               3.2  ...       1   versicolor
71                6.1               2.8  ...       1   versicolor
72                6.3               2.5  ...       1   versicolor
73                6.1               2.8  ...       1   versicolor
74                6.4               2.9  ...       1   versicolor
75                6.6               3.0  ...       1   versicolor
76                6.8               2.8  ...       1   versicolor
77                6.7               3.0  ...       1   versicolor
78                6.0               2.9  ...       1   versicolor
79                5.7               2.6  ...       1   versicolor
80                5.5               2.4  ...       1   versicolor
81                5.5               2.4  ...       1   versicolor
82                5.8               2.7  ...       1   versicolor
83                6.0               2.7  ...       1   versicolor
84                5.4               3.0  ...       1   versicolor
85                6.0               3.4  ...       1   versicolor
86                6.7               3.1  ...       1   versicolor
87                6.3               2.3  ...       1   versicolor
88                5.6               3.0  ...       1   versicolor
89                5.5               2.5  ...       1   versicolor
90                5.5               2.6  ...       1   versicolor
91                6.1               3.0  ...       1   versicolor
92                5.8               2.6  ...       1   versicolor
93                5.0               2.3  ...       1   versicolor
94                5.6               2.7  ...       1   versicolor
95                5.7               3.0  ...       1   versicolor
96                5.7               2.9  ...       1   versicolor
97                6.2               2.9  ...       1   versicolor
98                5.1               2.5  ...       1   versicolor
99                5.7               2.8  ...       1   versicolor

[50 rows x 6 columns]

In [28]:
X=df.iloc[:,0:-2]
X

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [30]:
y=df.iloc[:,-2]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Target, Length: 150, dtype: int32

In [31]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=101)

In [34]:
len(X_train)

120

In [35]:
len(y_test)

30

In [36]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [39]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [40]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [42]:
bagging_model=BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=5)
bagging_model.fit(X_train_scaled,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=5)

In [43]:
y_pred=bagging_model.predict(X_test_scaled)

In [44]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [45]:
from sklearn.ensemble import AdaBoostClassifier
AdaBoost=AdaBoostClassifier(n_estimators=10)

In [46]:
AdaBoost.fit(X_train_scaled,y_train)

AdaBoostClassifier(n_estimators=10)

In [48]:
y_predict=AdaBoost.predict(X_test_scaled)

In [49]:
accuracy_score(y_test,y_predict)

0.9333333333333333

In [51]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [52]:
#define base model
base_models=[
    ('tree', DecisionTreeClassifier()),
    ('svm',SVC(probability=True))
]
stacking_model=StackingClassifier(estimators=base_models,final_estimator=LogisticRegression())
stacking_model.fit(X_train_scaled,y_train)

StackingClassifier(estimators=[('tree', DecisionTreeClassifier()),
                               ('svm', SVC(probability=True))],
                   final_estimator=LogisticRegression())

In [54]:
y_pre=stacking_model.predict(X_test)

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(

In [55]:
accuracy_score(y_test,y_pre)

0.26666666666666666